clear all;
fclose('all');
pd = pwd;
cd([pd filesep strcat('mex_source',filesep)])
f = dir('*.c');
for i=1:length(f);
    mex([f(i).name],'-largeArrayDims');
end
if isunix()
    movefile('*.mexa64',[pd strcat(filesep,'dlls',filesep)]);
else
    movefile('*.mexw64',[pd strcat(filesep,'dlls',filesep)]);
end

baseDir = pd;
cd(baseDir);
dirList = {strcat('bootstrap',filesep),...
    strcat('crosssection',filesep),...
    strcat('distributions',filesep),...
    strcat('duplication',filesep),...
    strcat('GUI',filesep),...
    strcat('multivariate',filesep),...
    strcat('tests',filesep),...
    strcat('timeseries',filesep),...
    strcat('univariate',filesep),...
    strcat('utility',filesep),...
    strcat('mex_source',filesep),...
    strcat('dlls',filesep),...
    strcat('realized',filesep),...
    };
fileTypes = {'*.m','*.c','*.mexw32','*.mexw64','*.mat'};
fileAndDirList = cell(length(dirList)*length(fileTypes),1);
count = 1;
for i=1:length(dirList)
    for j=1:length(fileTypes)
        fileAndDirList{count} = [dirList{i} fileTypes{j}];
        count = count + 1;
    end
end
fileList = {'addToPath.m',...
    'Contents.m',...
    }';

fileAndDirList = [fileAndDirList; fileList];
zip([baseDir strcat(filesep,'MFEToolbox.zip')],fileAndDirList)
cd(baseDir)
%
% fileList = {'acf.m',...
%     'agarch.m',...
%     'agarch_core.m',...
%     'agarch_display.m',...
%     'agarch_itransform.m',...
%     'agarch_likelihood.m',...
%     'agarch_parameter_check.m',...
%     'agarch_simulate.m',...
%     'agarch_starting_values.m',...
%     'agarch_transform.m',...
%     'aicsbic.m',...
%     'aparch.m',...
%     'aparch_core.m',...
%     'aparch_itransform.m',...
%     'aparch_likelihood.m',...
%     'aparch_loglikelihood.m',...
%     'aparch_parameter_check.m',...
%     'aparch_simulate.m',...
%     'aparch_starting_values.m',...
%     'aparch_transform.m',...
%     'armaroots.m',...
%     'armaxerrors.m',...
%     'armaxfilter.m',...
%     'armaxfilter_core.m',...
%     'armaxfilter_likelihood.m',...
%     'armaxfilter_simulate.m',...
%     'arma_forecaster.m',...
%     'augdf.m',...
%     'augdfautolag.m',...
%     'augdfcv.m',...
%     'augdf_cvsim_tieup.m',...
%     'berkowitz.m',...
%     'beta_inv.m',...
%     'beta_pdf.m',...
%     'bkfilter.m',...
%     'c2mdate.m',...
%     'chi2cdf.m',...
%     'convert_ma_roots.m',...
%     'covnw.m',...
%     'covvar.m',...
%     'egarch.m',...
%     'egarch_core.m',...
%     'egarch_display.m',...
%     'egarch_itransform.m',...
%     'egarch_likelihood.m',...
%     'egarch_nlcon.m',...
%     'egarch_parameter_check.m',...
%     'egarch_simulate.m',...
%     'egarch_starting_values.m',...
%     'egarch_transform.m',...
%     'gedcdf.m',...
%     'gedinv.m',...
%     'gedloglik.m',...
%     'gedpdf.m',...
%     'gedrnd.m',...
%     'gradient_2sided.m',...
%     'grangercause.m',...
%     'hessian_2sided.m',...
%     'heterogeneousar.m',...
%     'hp_filter.m',...
%     'igarch.m',...
%     'igarch_core.m',...
%     'igarch_display.m',...
%     'igarch_itransform.m',...
%     'igarch_likelihood.m',...
%     'igarch_parameter_check.m',...
%     'igarch_starting_values.m',...
%     'igarch_transform.m',...
%     'impulseresponse.m',...
%     'inverse_ar_roots.m',...
%     'iscompatible.m',...
%     'ivech.m',...
%     'jarquebera.m',...
%     'kolmogorov.m',...
%     'kurtosis.m',...
%     'ljungbox.m',...
%     'lmtest1.m',...
%     'mprint.m',...
%     'mvnormloglik.m',...
%     'newlagmatrix.m',...
%     'normcdf.m',...
%     'norminv.m',...
%     'normloglik.m',...
%     'normpdf.m',...
%     'ols.m',...
%     'olsnw.m',...
%     'pacf.m',...
%     'pca.m',...
%     'pltdens.m',...
%     'robustvcv.m',...
%     'sacf.m',...
%     'skewtcdf.m',...
%     'skewtinv.m',...
%     'skewtloglik.m',...
%     'skewtpdf.m',...
%     'skewtrnd.m',...
%     'spacf.m',...
%     'standardize.m',...
%     'stdtcdf.m',...
%     'stdtinv.m',...
%     'stdtloglik.m',...
%     'stdtpdf.m',...
%     'stdtrnd.m',...
%     'tarch.m',...
%     'tarch_core.m',...
%     'tarch_display.m',...
%     'tarch_itransform.m',...
%     'tarch_likelihood.m',...
%     'tarch_parameter_check.m',...
%     'tarch_simulate.m',...
%     'tarch_starting_values.m',...
%     'tarch_transform.m',...
%     'tdis_inv.m',...
%     'tsresidualplot.m',...
%     'vectorar.m',...
%     'vectorarvcv.m',...
%     'x2mdate.m',...
%     'GDP.mat',...
%     'bsds.m',...
%     'stationary_bootstrap.m',...
%     'bsds.m',...
%     'block_bootstrap.m',...
%     'figarch.m',...
%     'figarch_itransform.m',...
%     'figarch_likelihood.m',...
%     'figarch_parameter_check.m',...
%     'figarch_simulate.m',...
%     'figarch_starting_values.m',...
%     'figarch_transform.m',...
%     'figarch_weights.m',...
%     'scalar_vt_vech.m',...
%     'scalar_vt_vech_itransform.m',...
%     'scalar_vt_vech_jointlikelihood.m',...
%     'scalar_vt_vech_likelihood.m',...
%     'scalar_vt_vech_simulate.m',...
%     'scalar_vt_vech_starting_values.m',...
%     'scalar_vt_vech_transform.m',...
%     'mcs.m',...
%     'hessian_2sided_nrows.m',...
%     'skewness.m',...
%     'vech.m',...
%     };


% d=dir('*.m');
% isAbsent = false(length(d),1);
% for i=1:length(d);
%     isAbsent(i) = ~ismember(d(i).name,fileList);
%     if isAbsent(i)
%         disp(d(i).name);
%     end
% end



dos('"C:\Program Files (x86)\Mozilla Firefox\firefox.exe" http://www.kevinsheppard.com/wiki/File:MFEToolbox.zip')